version: '2'
volumes:
  octoprint-data: {}
  traefik: {}
services:
  octoprint:
    build: ./octoprint
    restart: always
    volumes:
      - 'octoprint-data:/data'
    privileged: true
    ports:
      - '80:80'
      - '443:443'
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  octodash:
    restart: always
    build: ./octodash
    privileged: true
    environment:
     - UDEV=1
    depends_on:
     - octoprint
  mdns-publisher:
    build: ./mdns-publisher
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
